# 创建多维数组

In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a = np.ones([2,3])
a[1,2] = 2
print(a)

[[1. 1. 1.]
 [1. 1. 2.]]


In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

# 多维数组常用的属性

In [15]:
a = np.ones([2,3])
a.ndim

2

In [17]:
print(a.shape)

(2, 3)


In [18]:
a = np.matrix([[2,3],[3,4]])
print(a)
print(a.shape)

[[2 3]
 [3 4]]
(2, 2)


In [19]:
a.size

4

In [22]:
a.dtype

dtype('int32')

In [23]:
a.itemsize

4

In [34]:
a = np.arange(2000)
print(a)

[   0    1    2 ... 1997 1998 1999]


# 多维数组的基本操作

## 1.数组的算数运算

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a-b =",a-b)
print("a+b =",a+b)
print("a / b =",a/b)
print("a * b =", a*b)

a-b = [-3 -3 -3]
a+b = [5 7 9]
a / b = [0.25 0.4  0.5 ]
a * b = [ 4 10 18]


In [ ]:
# 矩阵乘法实现

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a*b = ",a*b)

c = a.dot(b)
print("matrix1: a*b =",c)

d = np.dot(a,b)
print("matrix2: a*b =",d)

a*b =  [ 4 10 18]
matrix1: a*b = 32
matrix2: a*b = 32


## 2数组的自身的

In [37]:
a = np.ones([2,3])

In [39]:
print(a.min())
print(a.max())
print(a.sum())

1.0
1.0
6.0


## 3随机数组

In [40]:
np.random.seed(42)
print(np.random.rand(2,3))
print(np.random.randn(2,3))
print(np.random.randint(1,10))
print(np.random.binomial(6,1))
print(np.random.beta(2,3))
print(np.random.normal(2,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
6
6
0.45543839870822056
2.666236704694229


## 索引 、切片和迭代

In [ ]:
基本与 list 的一样